---

services:

  # https://hub.docker.com/r/gitlab/gitlab-runner/tags
  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:alpine3.19-v16.10.0
    environment:
      TZ: ${ENV_TIMEZONE:-Europe/Berlin}
    volumes:
      - "./config:/etc/gitlab-runner"
      - "gitlab-runner-home:/home/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  gitlab-runner-home:
    external: true

...
